### ISSUE TITLE
When I dab others on the server don't see it

### ISSUE THREAD

**Issue by FlickySH** [MrCrayfish/MrCrayfishDabMod#3]
I know this mod is finished, but it will be nice to finalize it with some bug fixes

Plz fix this issue, it will be awesome

Aregev2

**Comment by MrCrayfish** [comment]
You have to be running on a Forge server with the mod installed.

**Comment by FlickySH** [comment]
I am

**Comment by MrCrayfish** [comment]
Does the server have the mod installed?

**Comment by FlickySH** [comment]
yes indeed


2018-01-22 16:10 GMT+02:00 MrCrayfish <notifications@github.com>:
